# Generated by Django 4.2.5 on 2023-09-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_alter_blog_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
